export const actionTypes = {
	SET_PRODUCTS: "SET_PRODUCTS",
	SELECTED_PRODUCTS: "SELECTED_PRODUCTS",
	REMOVE_SELECTED_PRODUCTS: "REMOVE_SELECTED_PRODUCTS",
	LOGIN_SUCCESS: 'LOGIN_SUCCESS',
	LOGIN_FAIL: 'LOGIN_FAIL',
};
